/*
 * Content Storage Service API
 * Content Storage Service provides storage and indexing for content and documents, which includes encryption/decryption of the content, anti-virus and authorization checks on upload and download. It is used by Content Metadata Service (CMS) when storing document objects, CMS will provide authorization management.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ot2.contentstorageservice.api;

import com.ot2.contentstorageservice.invoker.ApiCallback;
import com.ot2.contentstorageservice.invoker.ApiClient;
import com.ot2.contentstorageservice.invoker.ApiException;
import com.ot2.contentstorageservice.invoker.ApiResponse;
import com.ot2.contentstorageservice.invoker.Configuration;
import com.ot2.contentstorageservice.invoker.Pair;
import com.ot2.contentstorageservice.invoker.ProgressRequestBody;
import com.ot2.contentstorageservice.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.ot2.contentstorageservice.model.Content;
import com.ot2.contentstorageservice.model.Error;
import java.io.File;
import com.ot2.contentstorageservice.model.HttpProblem;
import com.ot2.contentstorageservice.model.UploadContentRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ContentApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ContentApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ContentApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for downloadcontent
     * @param id ID of the content (required)
     * @param objectId The ID of the object attached with the content (optional)
     * @param fileName The name of the file in response (optional)
     * @param mimeType The mime type of the content. This has higher priority than the Accept header (optional)
     * @param dispositionType Content disposition of the downloaded content (optional)
     * @param avsScan Flag indicating whether or not to perform a virus scan. Reserved for trusted clients, set false to skip avs (default is true) (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Content downloaded </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The endpoint cannot be reached because the request is not authorized </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Request failed </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call downloadcontentCall(String id, String objectId, String fileName, String mimeType, String dispositionType, Boolean avsScan, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/content/{id}/download"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (objectId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("object-id", objectId));
        }

        if (fileName != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("file-name", fileName));
        }

        if (mimeType != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("mime-type", mimeType));
        }

        if (dispositionType != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("disposition-type", dispositionType));
        }

        if (avsScan != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("avs-scan", avsScan));
        }

        final String[] localVarAccepts = {
            "application/octet-stream",
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "css.na-1-dev.api.opentext.com" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call downloadcontentValidateBeforeCall(String id, String objectId, String fileName, String mimeType, String dispositionType, Boolean avsScan, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling downloadcontent(Async)");
        }

        return downloadcontentCall(id, objectId, fileName, mimeType, dispositionType, avsScan, _callback);

    }

    /**
     * Download content
     * Download content
     * @param id ID of the content (required)
     * @param objectId The ID of the object attached with the content (optional)
     * @param fileName The name of the file in response (optional)
     * @param mimeType The mime type of the content. This has higher priority than the Accept header (optional)
     * @param dispositionType Content disposition of the downloaded content (optional)
     * @param avsScan Flag indicating whether or not to perform a virus scan. Reserved for trusted clients, set false to skip avs (default is true) (optional)
     * @return File
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Content downloaded </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The endpoint cannot be reached because the request is not authorized </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Request failed </td><td>  -  </td></tr>
     </table>
     */
    public File downloadcontent(String id, String objectId, String fileName, String mimeType, String dispositionType, Boolean avsScan) throws ApiException {
        ApiResponse<File> localVarResp = downloadcontentWithHttpInfo(id, objectId, fileName, mimeType, dispositionType, avsScan);
        return localVarResp.getData();
    }

    /**
     * Download content
     * Download content
     * @param id ID of the content (required)
     * @param objectId The ID of the object attached with the content (optional)
     * @param fileName The name of the file in response (optional)
     * @param mimeType The mime type of the content. This has higher priority than the Accept header (optional)
     * @param dispositionType Content disposition of the downloaded content (optional)
     * @param avsScan Flag indicating whether or not to perform a virus scan. Reserved for trusted clients, set false to skip avs (default is true) (optional)
     * @return ApiResponse&lt;File&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Content downloaded </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The endpoint cannot be reached because the request is not authorized </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Request failed </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<File> downloadcontentWithHttpInfo(String id, String objectId, String fileName, String mimeType, String dispositionType, Boolean avsScan) throws ApiException {
        okhttp3.Call localVarCall = downloadcontentValidateBeforeCall(id, objectId, fileName, mimeType, dispositionType, avsScan, null);
        Type localVarReturnType = new TypeToken<File>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Download content (asynchronously)
     * Download content
     * @param id ID of the content (required)
     * @param objectId The ID of the object attached with the content (optional)
     * @param fileName The name of the file in response (optional)
     * @param mimeType The mime type of the content. This has higher priority than the Accept header (optional)
     * @param dispositionType Content disposition of the downloaded content (optional)
     * @param avsScan Flag indicating whether or not to perform a virus scan. Reserved for trusted clients, set false to skip avs (default is true) (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Content downloaded </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The endpoint cannot be reached because the request is not authorized </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Request failed </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call downloadcontentAsync(String id, String objectId, String fileName, String mimeType, String dispositionType, Boolean avsScan, final ApiCallback<File> _callback) throws ApiException {

        okhttp3.Call localVarCall = downloadcontentValidateBeforeCall(id, objectId, fileName, mimeType, dispositionType, avsScan, _callback);
        Type localVarReturnType = new TypeToken<File>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getContent
     * @param id ID of the content (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Content downloaded </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The endpoint cannot be reached because the request is not authorized </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Request failed </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getContentCall(String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/content/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*",
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "css.na-1-dev.api.opentext.com" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getContentValidateBeforeCall(String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getContent(Async)");
        }

        return getContentCall(id, _callback);

    }

    /**
     * Get content metadata for the content
     * Get details of a specific content
     * @param id ID of the content (required)
     * @return Content
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Content downloaded </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The endpoint cannot be reached because the request is not authorized </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Request failed </td><td>  -  </td></tr>
     </table>
     */
    public Content getContent(String id) throws ApiException {
        ApiResponse<Content> localVarResp = getContentWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Get content metadata for the content
     * Get details of a specific content
     * @param id ID of the content (required)
     * @return ApiResponse&lt;Content&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Content downloaded </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The endpoint cannot be reached because the request is not authorized </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Request failed </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Content> getContentWithHttpInfo(String id) throws ApiException {
        okhttp3.Call localVarCall = getContentValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<Content>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get content metadata for the content (asynchronously)
     * Get details of a specific content
     * @param id ID of the content (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Content downloaded </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The endpoint cannot be reached because the request is not authorized </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Request failed </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getContentAsync(String id, final ApiCallback<Content> _callback) throws ApiException {

        okhttp3.Call localVarCall = getContentValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<Content>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for uploadContent
     * @param uploadContentRequest Pass binary data via multipart/form-data or in plain body (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Content uploaded successfully </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The endpoint cannot be reached because the request is not authorized </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Request failed </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call uploadContentCall(UploadContentRequest uploadContentRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = uploadContentRequest;

        // create path and map variables
        String localVarPath = "/v2/content";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "multipart/form-data",
            "application/octet-stream"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "css.na-1-dev.api.opentext.com" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call uploadContentValidateBeforeCall(UploadContentRequest uploadContentRequest, final ApiCallback _callback) throws ApiException {
        return uploadContentCall(uploadContentRequest, _callback);

    }

    /**
     * Tenant user upload content
     * Tenant user upload content
     * @param uploadContentRequest Pass binary data via multipart/form-data or in plain body (optional)
     * @return Content
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Content uploaded successfully </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The endpoint cannot be reached because the request is not authorized </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Request failed </td><td>  -  </td></tr>
     </table>
     */
    public Content uploadContent(UploadContentRequest uploadContentRequest) throws ApiException {
        ApiResponse<Content> localVarResp = uploadContentWithHttpInfo(uploadContentRequest);
        return localVarResp.getData();
    }

    /**
     * Tenant user upload content
     * Tenant user upload content
     * @param uploadContentRequest Pass binary data via multipart/form-data or in plain body (optional)
     * @return ApiResponse&lt;Content&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Content uploaded successfully </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The endpoint cannot be reached because the request is not authorized </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Request failed </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Content> uploadContentWithHttpInfo(UploadContentRequest uploadContentRequest) throws ApiException {
        okhttp3.Call localVarCall = uploadContentValidateBeforeCall(uploadContentRequest, null);
        Type localVarReturnType = new TypeToken<Content>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Tenant user upload content (asynchronously)
     * Tenant user upload content
     * @param uploadContentRequest Pass binary data via multipart/form-data or in plain body (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Content uploaded successfully </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The endpoint cannot be reached because the request is not authorized </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Request failed </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call uploadContentAsync(UploadContentRequest uploadContentRequest, final ApiCallback<Content> _callback) throws ApiException {

        okhttp3.Call localVarCall = uploadContentValidateBeforeCall(uploadContentRequest, _callback);
        Type localVarReturnType = new TypeToken<Content>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for uploadContentTenant
     * @param tenantId ID of tenant (required)
     * @param avsScan Flag indicating whether or not to perform a virus scan. Reserved for trusted clients, set false to skip avs (default is true) (optional)
     * @param uploadContentRequest Pass binary data via multipart/form-data or in plain body (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Content uploaded successfully </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The endpoint cannot be reached because the request is not authorized </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Request failed </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call uploadContentTenantCall(String tenantId, Boolean avsScan, UploadContentRequest uploadContentRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = uploadContentRequest;

        // create path and map variables
        String localVarPath = "/v2/tenant/{tenantId}/content"
            .replace("{" + "tenantId" + "}", localVarApiClient.escapeString(tenantId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (avsScan != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("avs-scan", avsScan));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "multipart/form-data",
            "application/octet-stream"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "css.na-1-dev.api.opentext.com" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call uploadContentTenantValidateBeforeCall(String tenantId, Boolean avsScan, UploadContentRequest uploadContentRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'tenantId' is set
        if (tenantId == null) {
            throw new ApiException("Missing the required parameter 'tenantId' when calling uploadContentTenant(Async)");
        }

        return uploadContentTenantCall(tenantId, avsScan, uploadContentRequest, _callback);

    }

    /**
     * Upload content for a tenant
     * Upload content for a tenant
     * @param tenantId ID of tenant (required)
     * @param avsScan Flag indicating whether or not to perform a virus scan. Reserved for trusted clients, set false to skip avs (default is true) (optional)
     * @param uploadContentRequest Pass binary data via multipart/form-data or in plain body (optional)
     * @return Content
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Content uploaded successfully </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The endpoint cannot be reached because the request is not authorized </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Request failed </td><td>  -  </td></tr>
     </table>
     */
    public Content uploadContentTenant(String tenantId, Boolean avsScan, UploadContentRequest uploadContentRequest) throws ApiException {
        ApiResponse<Content> localVarResp = uploadContentTenantWithHttpInfo(tenantId, avsScan, uploadContentRequest);
        return localVarResp.getData();
    }

    /**
     * Upload content for a tenant
     * Upload content for a tenant
     * @param tenantId ID of tenant (required)
     * @param avsScan Flag indicating whether or not to perform a virus scan. Reserved for trusted clients, set false to skip avs (default is true) (optional)
     * @param uploadContentRequest Pass binary data via multipart/form-data or in plain body (optional)
     * @return ApiResponse&lt;Content&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Content uploaded successfully </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The endpoint cannot be reached because the request is not authorized </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Request failed </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Content> uploadContentTenantWithHttpInfo(String tenantId, Boolean avsScan, UploadContentRequest uploadContentRequest) throws ApiException {
        okhttp3.Call localVarCall = uploadContentTenantValidateBeforeCall(tenantId, avsScan, uploadContentRequest, null);
        Type localVarReturnType = new TypeToken<Content>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Upload content for a tenant (asynchronously)
     * Upload content for a tenant
     * @param tenantId ID of tenant (required)
     * @param avsScan Flag indicating whether or not to perform a virus scan. Reserved for trusted clients, set false to skip avs (default is true) (optional)
     * @param uploadContentRequest Pass binary data via multipart/form-data or in plain body (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Content uploaded successfully </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The endpoint cannot be reached because the request is not authorized </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Request failed </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call uploadContentTenantAsync(String tenantId, Boolean avsScan, UploadContentRequest uploadContentRequest, final ApiCallback<Content> _callback) throws ApiException {

        okhttp3.Call localVarCall = uploadContentTenantValidateBeforeCall(tenantId, avsScan, uploadContentRequest, _callback);
        Type localVarReturnType = new TypeToken<Content>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for uploadContentURL
     * @param id ID of upload (required)
     * @param avsScan Flag indicating whether or not to perform a virus scan. Reserved for trusted clients, set false to skip avs (default is true) (optional)
     * @param uploadContentRequest Pass binary data via multipart/form-data or in plain body (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Content uploaded successfully </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The endpoint cannot be reached because the request is not authorized </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Request failed </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call uploadContentURLCall(String id, Boolean avsScan, UploadContentRequest uploadContentRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = uploadContentRequest;

        // create path and map variables
        String localVarPath = "/v2/upload/{id}/content"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (avsScan != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("avs-scan", avsScan));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "multipart/form-data",
            "application/octet-stream"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "css.na-1-dev.api.opentext.com" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call uploadContentURLValidateBeforeCall(String id, Boolean avsScan, UploadContentRequest uploadContentRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling uploadContentURL(Async)");
        }

        return uploadContentURLCall(id, avsScan, uploadContentRequest, _callback);

    }

    /**
     * Upload content with upload URL
     * Upload content with upload URL
     * @param id ID of upload (required)
     * @param avsScan Flag indicating whether or not to perform a virus scan. Reserved for trusted clients, set false to skip avs (default is true) (optional)
     * @param uploadContentRequest Pass binary data via multipart/form-data or in plain body (optional)
     * @return Content
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Content uploaded successfully </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The endpoint cannot be reached because the request is not authorized </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Request failed </td><td>  -  </td></tr>
     </table>
     */
    public Content uploadContentURL(String id, Boolean avsScan, UploadContentRequest uploadContentRequest) throws ApiException {
        ApiResponse<Content> localVarResp = uploadContentURLWithHttpInfo(id, avsScan, uploadContentRequest);
        return localVarResp.getData();
    }

    /**
     * Upload content with upload URL
     * Upload content with upload URL
     * @param id ID of upload (required)
     * @param avsScan Flag indicating whether or not to perform a virus scan. Reserved for trusted clients, set false to skip avs (default is true) (optional)
     * @param uploadContentRequest Pass binary data via multipart/form-data or in plain body (optional)
     * @return ApiResponse&lt;Content&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Content uploaded successfully </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The endpoint cannot be reached because the request is not authorized </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Request failed </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Content> uploadContentURLWithHttpInfo(String id, Boolean avsScan, UploadContentRequest uploadContentRequest) throws ApiException {
        okhttp3.Call localVarCall = uploadContentURLValidateBeforeCall(id, avsScan, uploadContentRequest, null);
        Type localVarReturnType = new TypeToken<Content>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Upload content with upload URL (asynchronously)
     * Upload content with upload URL
     * @param id ID of upload (required)
     * @param avsScan Flag indicating whether or not to perform a virus scan. Reserved for trusted clients, set false to skip avs (default is true) (optional)
     * @param uploadContentRequest Pass binary data via multipart/form-data or in plain body (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Content uploaded successfully </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The endpoint cannot be reached because the request is not authorized </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Request failed </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call uploadContentURLAsync(String id, Boolean avsScan, UploadContentRequest uploadContentRequest, final ApiCallback<Content> _callback) throws ApiException {

        okhttp3.Call localVarCall = uploadContentURLValidateBeforeCall(id, avsScan, uploadContentRequest, _callback);
        Type localVarReturnType = new TypeToken<Content>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
