/*
 * Core Capture Services
 * OpenText Core Capture Services are a set of RESTful web service interfaces that provides capture functionality. Being developed in a purely RESTful style, Core Capture Services are easier to consume for the purposes of writing custom clients.  Core Capture Services identifies resources by Uniform Resource Identifiers (URIs). It defines specific media types to represent resources and drives application state transfers by using link relations. It uses a limited number of HTTP standard methods (GET, POST, and DELETE) to manipulate these resources over the HTTP protocol.  Core Capture Services (hereafter simply called, \"service\") supports only the JSON format for resource representation. JavaScript Object Notation (JSON) is a lightweight data interchange format based on a subset of the JavaScript Programming Language standard.
 *
 * The version of the OpenAPI document: 23.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ot2.corecapture.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ot2.corecapture.model.DocItemContentContentFieldsInnerUiControlInfoRectangle;
import com.ot2.corecapture.model.UimDataNodeListInnerDataInnerChoicesInner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DocItemContentContentFieldsInnerUiControlInfo
 */
public class DocItemContentContentFieldsInnerUiControlInfoTest {
    private final DocItemContentContentFieldsInnerUiControlInfo model = new DocItemContentContentFieldsInnerUiControlInfo();

    /**
     * Model tests for DocItemContentContentFieldsInnerUiControlInfo
     */
    @Test
    public void testDocItemContentContentFieldsInnerUiControlInfo() {
        // TODO: test DocItemContentContentFieldsInnerUiControlInfo
    }

    /**
     * Test the property 'controlType'
     */
    @Test
    public void controlTypeTest() {
        // TODO: test controlType
    }

    /**
     * Test the property 'labelText'
     */
    @Test
    public void labelTextTest() {
        // TODO: test labelText
    }

    /**
     * Test the property 'tooltip'
     */
    @Test
    public void tooltipTest() {
        // TODO: test tooltip
    }

    /**
     * Test the property 'choices'
     */
    @Test
    public void choicesTest() {
        // TODO: test choices
    }

    /**
     * Test the property 'multiLine'
     */
    @Test
    public void multiLineTest() {
        // TODO: test multiLine
    }

    /**
     * Test the property 'rectangle'
     */
    @Test
    public void rectangleTest() {
        // TODO: test rectangle
    }

    /**
     * Test the property 'labelRectangle'
     */
    @Test
    public void labelRectangleTest() {
        // TODO: test labelRectangle
    }

}
