/*
 * Core Capture Services
 * OpenText Core Capture Services are a set of RESTful web service interfaces that provides capture functionality. Being developed in a purely RESTful style, Core Capture Services are easier to consume for the purposes of writing custom clients.  Core Capture Services identifies resources by Uniform Resource Identifiers (URIs). It defines specific media types to represent resources and drives application state transfers by using link relations. It uses a limited number of HTTP standard methods (GET, POST, and DELETE) to manipulate these resources over the HTTP protocol.  Core Capture Services (hereafter simply called, \"service\") supports only the JSON format for resource representation. JavaScript Object Notation (JSON) is a lightweight data interchange format based on a subset of the JavaScript Programming Language standard.
 *
 * The version of the OpenAPI document: 23.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ot2.corecapture;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ot2.corecapture.BasicResultItemWithValuesAndFiles;
import com.ot2.corecapture.ReturnStatusBody;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SessionServicesConvertimagesPost200Response
 */
public class SessionServicesConvertimagesPost200ResponseTest {
    private final SessionServicesConvertimagesPost200Response model = new SessionServicesConvertimagesPost200Response();

    /**
     * Model tests for SessionServicesConvertimagesPost200Response
     */
    @Test
    public void testSessionServicesConvertimagesPost200Response() {
        // TODO: test SessionServicesConvertimagesPost200Response
    }

    /**
     * Test the property 'returnStatus'
     */
    @Test
    public void returnStatusTest() {
        // TODO: test returnStatus
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'serviceName'
     */
    @Test
    public void serviceNameTest() {
        // TODO: test serviceName
    }

    /**
     * Test the property 'executionMilliSeconds'
     */
    @Test
    public void executionMilliSecondsTest() {
        // TODO: test executionMilliSeconds
    }

    /**
     * Test the property 'licenseUsedPercent'
     */
    @Test
    public void licenseUsedPercentTest() {
        // TODO: test licenseUsedPercent
    }

    /**
     * Test the property 'licensePagesUsed'
     */
    @Test
    public void licensePagesUsedTest() {
        // TODO: test licensePagesUsed
    }

    /**
     * Test the property 'licensePagesUsed2'
     */
    @Test
    public void licensePagesUsed2Test() {
        // TODO: test licensePagesUsed2
    }

    /**
     * Test the property 'resultItems'
     */
    @Test
    public void resultItemsTest() {
        // TODO: test resultItems
    }

}
